/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author pf3k6
 */
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import java.sql.*;



public class MenuPenjualanRumah extends javax.swing.JFrame {

    /**
     * Creates new form MenuPenjualanRumah
     */
    public MenuPenjualanRumah() {
        initComponents();
        
        // Grupkan radio button
        ButtonGroup group = new ButtonGroup();
        group.add(jRadioButton1);
        group.add(jRadioButton2);
        group.add(jRadioButton3);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtfNamaPemesan = new javax.swing.JTextField();
        txtfHargaTanah = new javax.swing.JTextField();
        cmbboxArea = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtfHargaBangunan = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        txtfLuasTanahAsli = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtfLuasTanahTersedia = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtfHarga = new javax.swing.JTextField();
        txtfDp = new javax.swing.JTextField();
        txtfLamaCicilan = new javax.swing.JTextField();
        txtfPpn = new javax.swing.JTextField();
        txtfCicilan = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        btnProses = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nama Pemesan");

        jLabel2.setText("Harga Tanah/m2");

        jLabel3.setText("Area");

        txtfNamaPemesan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfNamaPemesanActionPerformed(evt);
            }
        });

        txtfHargaTanah.setEditable(false);

        cmbboxArea.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Pilih Area--", "Bougenvile", "Melati", "Flamboyan" }));
        cmbboxArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbboxAreaActionPerformed(evt);
            }
        });

        jLabel4.setText("Harga Bangunan");

        txtfHargaBangunan.setEditable(false);
        txtfHargaBangunan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfHargaBangunanActionPerformed(evt);
            }
        });

        jLabel5.setText("Tipe Rumah");

        jLabel6.setText("Luas Tanah Asli");

        jRadioButton1.setText("Tipe-36");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jRadioButton2.setText("Tipe-54");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        jRadioButton3.setText("Tipe-45");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        txtfLuasTanahAsli.setEditable(false);
        txtfLuasTanahAsli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfLuasTanahAsliActionPerformed(evt);
            }
        });

        jLabel7.setText("Luas Tanah Tersedia");

        txtfLuasTanahTersedia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfLuasTanahTersediaActionPerformed(evt);
            }
        });

        jLabel8.setText("Harga");

        jLabel9.setText("DP");

        jLabel10.setText("Lama Cicilan");

        jLabel11.setText("PPN (10%)");

        jLabel12.setText("Cicilan/bln");

        txtfHarga.setEditable(false);

        txtfDp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfDpActionPerformed(evt);
            }
        });

        txtfPpn.setEditable(false);

        txtfCicilan.setEditable(false);

        jLabel13.setText("Bulan");

        jCheckBox1.setText("Setuju");

        btnProses.setText("Proses");
        btnProses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProsesActionPerformed(evt);
            }
        });

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtfNamaPemesan)
                    .addComponent(txtfHargaTanah)
                    .addComponent(cmbboxArea, 0, 151, Short.MAX_VALUE))
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnProses)
                        .addGap(43, 43, 43)
                        .addComponent(btnSimpan)
                        .addGap(32, 32, 32)
                        .addComponent(btnClear))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jRadioButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRadioButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(txtfHargaBangunan, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtfLuasTanahAsli, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(txtfLuasTanahTersedia, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtfHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtfDp, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtfLamaCicilan, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtfPpn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtfCicilan, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(0, 45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtfNamaPemesan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtfHargaBangunan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtfHargaTanah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(cmbboxArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jRadioButton1)
                            .addComponent(txtfLuasTanahAsli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButton3)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButton2)
                            .addComponent(txtfLuasTanahTersedia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtfHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtfDp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtfLamaCicilan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtfPpn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtfCicilan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox1))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnProses)
                    .addComponent(btnSimpan)
                    .addComponent(btnClear))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbboxAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbboxAreaActionPerformed
        // TODO add your handling code here:
        String selectedArea = cmbboxArea.getSelectedItem().toString();

    switch (selectedArea) {
        case "Bougenvile":
            txtfHargaTanah.setText("600000");
            txtfHargaBangunan.setText("95000000");
            break;
        case "Melati":
            txtfHargaTanah.setText("700000");
            txtfHargaBangunan.setText("125000000");
            break;
        case "Flamboyan":
            txtfHargaTanah.setText("800000");
            txtfHargaBangunan.setText("155000000");
            break;
        default:
            txtfHargaTanah.setText("");
            txtfHargaBangunan.setText("");
            break;
        }
    }//GEN-LAST:event_cmbboxAreaActionPerformed

    private void txtfNamaPemesanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfNamaPemesanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfNamaPemesanActionPerformed

    private void txtfHargaBangunanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfHargaBangunanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfHargaBangunanActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
        txtfLuasTanahAsli.setText("72");
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void txtfLuasTanahAsliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfLuasTanahAsliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfLuasTanahAsliActionPerformed

    private void txtfLuasTanahTersediaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfLuasTanahTersediaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfLuasTanahTersediaActionPerformed

    private void txtfDpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfDpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfDpActionPerformed

    private void btnProsesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProsesActionPerformed
        // TODO add your handling code here:
        try {
            double hargaTanah = Double.parseDouble(txtfHargaTanah.getText());
            double hargaBangunan = Double.parseDouble(txtfHargaBangunan.getText());
            double luasTanah = Double.parseDouble(txtfLuasTanahTersedia.getText());
            double dp = Double.parseDouble(txtfDp.getText());
            int lamaCicilan = Integer.parseInt(txtfLamaCicilan.getText());

            double harga = (luasTanah * hargaTanah) + hargaBangunan;
            double ppn = 0.1 * harga;
            double cicilan = (harga + ppn - dp) / lamaCicilan;

            txtfHarga.setText(String.format("%.2f", harga));
            txtfPpn.setText(String.format("%.2f", ppn));
            txtfCicilan.setText(String.format("%.2f", cicilan));

            String tipe = jRadioButton1.isSelected() ? "T-36" : (jRadioButton3.isSelected() ? "T-45" : (jRadioButton2.isSelected() ? "T-54" : ""));
            String pesan = "Apakah data yang dimasukkan sudah benar?\n\n"
                    + "Nama: " + txtfNamaPemesan.getText() + "\n"
                    + "Area: " + cmbboxArea.getSelectedItem().toString() + "\n"
                    + "Tipe Rumah: " + tipe + "\n"
                    + "Harga: Rp " + txtfHarga.getText() + "\n"
                    + "PPn (10%): Rp " + txtfPpn.getText() + "\n"
                    + "Cicilan/Bulan: Rp " + txtfCicilan.getText();

            int konfirmasi = JOptionPane.showConfirmDialog(this, pesan, "Konfirmasi Data", JOptionPane.YES_NO_OPTION);
            if (konfirmasi == JOptionPane.YES_OPTION) {
                JOptionPane.showMessageDialog(this, "Data dikonfirmasi.");
            } else {
                JOptionPane.showMessageDialog(this, "Silakan periksa kembali data Anda.");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan input. Pastikan semua data terisi dengan benar.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnProsesActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
        txtfLuasTanahAsli.setText("90");
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
        txtfLuasTanahAsli.setText("120");
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        txtfNamaPemesan.setText("");
        cmbboxArea.setSelectedIndex(0);
        txtfHargaTanah.setText("");
        txtfHargaBangunan.setText("");
        txtfLuasTanahAsli.setText("");
        txtfLuasTanahTersedia.setText("");
        txtfHarga.setText("");
        txtfDp.setText("");
        txtfLamaCicilan.setText("");
        txtfPpn.setText("");
        txtfCicilan.setText("");
        jCheckBox1.setSelected(false);

        ButtonGroup group = new ButtonGroup();
        group.add(jRadioButton1);
        group.add(jRadioButton2);
        group.add(jRadioButton3);
        group.clearSelection();
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        if (!jCheckBox1.isSelected()) {
        JOptionPane.showMessageDialog(this, "Anda harus mencentang persetujuan terlebih dahulu.", "Peringatan", JOptionPane.WARNING_MESSAGE);
        return;
    }

    try {
        Connection conn = Koneksi.getConnection();
        String sql = "INSERT INTO transaksi (nama_pemesan, area, tipe_rumah, luas_tanah_tersedia, harga_total, lama_cicilan, cicilan_per_bulan) " +
                     "VALUES (?, ?, ?, ?, ?, ?, ?)";
        PreparedStatement pst = conn.prepareStatement(sql);

        String tipe = jRadioButton1.isSelected() ? "T-36" :
                      (jRadioButton3.isSelected() ? "T-45" :
                      (jRadioButton2.isSelected() ? "T-54" : ""));

        // Hapus karakter pemisah ribuan dan parsing angka
        String hargaRaw = txtfHarga.getText().replace(".", "").replace(",", "").replace(" ", "");
        String cicilanRaw = txtfCicilan.getText().replace(".", "").replace(",", "").replace(" ", "");

        long harga = Long.parseLong(hargaRaw);
        long cicilan = Long.parseLong(cicilanRaw);
        int lamaCicilan = Integer.parseInt(txtfLamaCicilan.getText());

        pst.setString(1, txtfNamaPemesan.getText());
        pst.setString(2, cmbboxArea.getSelectedItem().toString());
        pst.setString(3, tipe);
        pst.setDouble(4, Double.parseDouble(txtfLuasTanahTersedia.getText()));
        pst.setLong(5, harga);
        pst.setInt(6, lamaCicilan);
        pst.setLong(7, cicilan);

        pst.executeUpdate();
        JOptionPane.showMessageDialog(this, "Data berhasil disimpan ke database.");
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Gagal menyimpan data: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnSimpanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPenjualanRumah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPenjualanRumah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPenjualanRumah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPenjualanRumah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPenjualanRumah().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnProses;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JComboBox<String> cmbboxArea;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JTextField txtfCicilan;
    private javax.swing.JTextField txtfDp;
    private javax.swing.JTextField txtfHarga;
    private javax.swing.JTextField txtfHargaBangunan;
    private javax.swing.JTextField txtfHargaTanah;
    private javax.swing.JTextField txtfLamaCicilan;
    private javax.swing.JTextField txtfLuasTanahAsli;
    private javax.swing.JTextField txtfLuasTanahTersedia;
    private javax.swing.JTextField txtfNamaPemesan;
    private javax.swing.JTextField txtfPpn;
    // End of variables declaration//GEN-END:variables
}
